worker_processes 1;
events { worker_connections 1024; }
stream {
    map $ssl_preread_server_name $backend_443 {
        ~*\.admin\.uds\.dev  10.200.34.200:443;
        default              10.200.34.201:443;
    }
    map $ssl_preread_server_name $backend_80 {
        ~*\.admin\.uds\.dev  10.200.34.200:80;
        default              10.200.34.201:80;
    }
    server { listen 443; proxy_pass $backend_443; ssl_preread on; }
    server { listen 80; proxy_pass $backend_80; }
}
