// Code generated by hand to satisfy runtime.Object without requiring
// controller-gen tooling. LabSessionSpec/Status contain only value types
// (strings, bool, metav1.Time), so a shallow struct copy is a deep copy for
// them; ObjectMeta/ListMeta and the Items slice are copied explicitly.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

// DeepCopyInto copies the receiver into out.
func (in *LabSession) DeepCopyInto(out *LabSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy returns a deep copy of the receiver.
func (in *LabSession) DeepCopy() *LabSession {
	if in == nil {
		return nil
	}
	out := new(LabSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *LabSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *LabSessionSpec) DeepCopyInto(out *LabSessionSpec) {
	*out = *in
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy returns a deep copy of the receiver.
func (in *LabSessionSpec) DeepCopy() *LabSessionSpec {
	if in == nil {
		return nil
	}
	out := new(LabSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *LabSessionStatus) DeepCopyInto(out *LabSessionStatus) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *LabSessionStatus) DeepCopy() *LabSessionStatus {
	if in == nil {
		return nil
	}
	out := new(LabSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *LabSessionList) DeepCopyInto(out *LabSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		items := make([]LabSession, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&items[i])
		}
		out.Items = items
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *LabSessionList) DeepCopy() *LabSessionList {
	if in == nil {
		return nil
	}
	out := new(LabSessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *LabSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
